# Generated by Django 4.1.6 on 2023-02-12 04:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('AKTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=30)),
                ('character_rare', models.IntegerField()),
                ('tags', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=88, size=8)),
            ],
        ),
    ]
